### PR TITLE
feat: files api get recently published files

### PR DESCRIPTION
**Pull request by zanderson3j**
Adds list recently published files to Files Api: https://api-reference.smartling.com/#tag/Files/operation/getRecentlyPublishedFilesList

### CODE REVIEW

**Comment by zanderson3j** [comment]
Looks like this is actually under /published-files-api and not /files-api, so I need to make some updates.

**Comment by zanderson3j** [comment]
> Looks like this is actually under /published-files-api and not /files-api, so I need to make some updates.

updated

**Comment by dimitrystd** [comment]
Hi @zanderson3j, I discussed this PR with the team and discovered that we have an SDK for this API, but it is "internal". We will merge (or replace) your code with ours. However, due to the holiday season, it may take a few days.

**Comment by zanderson3j** [comment]
> Hi @zanderson3j, I discussed this PR with the team and discovered that we have an SDK for this API, but it is "internal". We will merge (or replace) your code with ours. However, due to the holiday season, it may take a few days.

Sounds good, thanks @dimitrystd!

**Comment by PavelLoparev** [comment]
Hi @zanderson3j `smartling-api-sdk-nodejs 2.7.0` is released (I've moved this api client from our "internal" sdk to this public one, [it's almost the same](https://github.com/Smartling/api-sdk-nodejs/pull/101) as your code though).

I will close this PR.

**Pull request closed without merging**
